##########
# collectionbuilder-csv
# Jekyll Digital Collection Generator
# https://github.com/CollectionBuilder/collectionbuilder-csv
##########

##########
# URL VARIABLES
#
# site domain, full URL to the production location of your collection
url: https://zarrow.library.okstate.edu
# path to location on the domain if necessary e.g. /digital/hjccc
baseurl: 
# location of code, the full url to your github repository
source-code: #https://github.com/CollectionBuilder/collectionbuilder-csv

##########
# SITE SETTINGS
#
# title of site appears in banner
title: The Maxine & Jack Zarrow Collection
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: a tour through the collection
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "The Maxine and Jack Zarrow Collection includes over 500 works of art from around the world. The collection is composed primarily of paintings, mixed media works and sculptures by Native American artists including Fred Beaver, Harrison Begay, Woody Crumbo, Brummett Echohawk, Gina Gray, Benjamin Harjo Jr., Allan Houser, Mopope, Bill Rabbit, Ben Adair Shoemaker, Kugee Supernaw, Jerome Tiger, Dick West and Charles Banks Wilson. This website provides a look into the Maxine and Jack Zarrow Collection using metadata carefully curated through the years."

# keywords, a short list of subjects describing the collection, separated by semicolon, to appear in rich markup
keywords: oklahoma;history;native america
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: Oklahoma State University Library
# Organization branding #if we choose to activate these, uncomment below AND uncomment lines in collection-banner.html in the include file
#organization-name:
#organization-link: 
organization-logo-banner: objects/dc-logo-trans.png
organization-logo-nav: objects/dc-logo-trans.png

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the CSV file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: metadata-zarrow-final
# page generation settings [optional!]
# [optional: only used if you need to tweak CB defaults or generate from more than one data file]
# page_gen:
#   - data: 'demo-metadata'
#     template: 'item'
#     name: 'objectid'
#     dir: 'items'
#     extension: 'html' 
#     filter: 'objectid'  

##########
# GOOGLE SERVICES [optional!]
#
# leave these blank or comment out to NOT include google code
# if present, used to add analytics during "production" build only
# google-analytics-id: "UA-74844011-1"
# google-cse-id: "002151703305773322890:1pu3smhw1t8"

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE]
# compress CSS output
sass:
  style: compressed
